using System;
using System.Collections.Generic;
using System.IO.Abstractions;

namespace FileCategorizationUtilityServices;

/// <summary>
/// Implementation of <see cref="IFileExtensionChecker"/> that uses <see cref="IFileSystem"/> for file operations.
/// </summary>
public class FileExtensionChecker : IFileExtensionChecker
{
    private static readonly HashSet<string> _configExt = new(StringComparer.OrdinalIgnoreCase)
    {
        ".json",
        ".json5",
        ".config",
        ".xml",
        ".props",
        ".targets",
    };

    private static readonly HashSet<string> _documentationExt = new(StringComparer.OrdinalIgnoreCase)
    {
        ".md",
        ".docx",
        ".doc",
    };

    private static readonly HashSet<string> _solutionExt = new(StringComparer.OrdinalIgnoreCase)
    {
        ".sln",
        ".slnx",
    };

    private static readonly HashSet<string> _projectExt = new(StringComparer.OrdinalIgnoreCase)
    {
        ".csproj"
    };

    private static readonly HashSet<string> _programmingLanguageExt = new(StringComparer.OrdinalIgnoreCase)
    {
        ".cs", // C#
        ".g.cs", // C# generated by source generator
        ".vb", // visual basic
        ".fs", // F# source code
        ".fsx", // F# script
        ".fsi", // F# script interface
    };

    private static readonly HashSet<string> _textExt = new(StringComparer.OrdinalIgnoreCase)
    {
        ".txt",
    };

    private readonly IFileSystem _fileSystem;

    /// <summary>
    /// Initializes a new instance of the <see cref="FileExtensionChecker"/> class.
    /// </summary>
    /// <param name="fileSystem">The file system abstraction to use.</param>
    /// <exception cref="ArgumentNullException">Thrown when <paramref name="fileSystem"/> is null.</exception>
    public FileExtensionChecker(IFileSystem fileSystem)
    {
        ArgumentNullException.ThrowIfNull(fileSystem);
        _fileSystem = fileSystem;
    }

    /// <inheritdoc/>
    public bool IsConfiguration(string filePath)
    {
        ArgumentException.ThrowIfNullOrEmpty(filePath);
        return _fileSystem.File.Exists(filePath) && filePath.GetFileExtension().IsOneOf(_configExt);
    }

    /// <inheritdoc/>
    public bool IsDocument(string filePath)
    {
        ArgumentException.ThrowIfNullOrEmpty(filePath);
        return _fileSystem.File.Exists(filePath) && filePath.GetFileExtension().IsOneOf(_documentationExt);
    }

    /// <inheritdoc/>
    public bool IsSolution(string filePath)
    {
        ArgumentException.ThrowIfNullOrEmpty(filePath);
        return _fileSystem.File.Exists(filePath) && filePath.GetFileExtension().IsOneOf(_solutionExt);
    }

    /// <inheritdoc/>
    public bool IsProject(string filePath)
    {
        ArgumentException.ThrowIfNullOrEmpty(filePath);
        return _fileSystem.File.Exists(filePath) && filePath.GetFileExtension().IsOneOf(_projectExt);
    }

    /// <inheritdoc/>
    public bool IsProgrammingLanguage(string filePath)
    {
        ArgumentException.ThrowIfNullOrEmpty(filePath);
        return _fileSystem.File.Exists(filePath) && filePath.GetFileExtension().IsOneOf(_programmingLanguageExt);
    }

    /// <inheritdoc/>
    public bool IsText(string filePath)
    {
        ArgumentException.ThrowIfNullOrEmpty(filePath);
        return _fileSystem.File.Exists(filePath) && filePath.GetFileExtension().IsOneOf(_textExt);
    }

    /// <inheritdoc/>
    public bool NeedsToBeReplaced(string filePath)
    {
        ArgumentException.ThrowIfNullOrEmpty(filePath);
        return IsConfiguration(filePath) ||
               IsDocument(filePath) ||
               IsSolution(filePath) ||
               IsProject(filePath) ||
               IsProgrammingLanguage(filePath) ||
               IsText(filePath);
    }
}
