using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Testing;
using Microsoft.CodeAnalysis.Testing;
using Microsoft.CodeAnalysis.Text;
using SourceGeneratorUtilityServices.Generators;
using System;
using System.Collections.Generic;
using System.Text;
using System.Threading.Tasks;
using Xunit;
using Xunit.Abstractions;
using Xunit.Sdk;

namespace SourceGeneratorUtilityServices.xUnit.Tests
{
    public class DbContextInterfaceGeneratorTests
    {
        private readonly ITestOutputHelper _output;
        public DbContextInterfaceGeneratorTests(ITestOutputHelper output)
        {
            _output = output;
        }

        [Fact]
        public async Task Generator_ShouldGenerateInterface_WhenClassIsInBeansNamespace_FuzzyMatch()
        {

                string inputSource = @"
namespace MyProject.Beans
{
    public class UserBean
    {
        public int Id { get; set; }
    }
}";

                string expectedOutput = $$"""
// <auto-generated/>
#nullable enable
using Microsoft.EntityFrameworkCore;

namespace MyProject.Interfaces
{
    /// <summary>
    /// 自動生成的 UserBean 資料庫上下文介面
    /// </summary>
    public partial interface IUserBeanContext
    {
        DbSet<global::MyProject.Beans.UserBean> UserBeans { get; set; }
    }
}
""";

                var tester = new CSharpIncrementalGeneratorTest<DbContextInterfaceGenerator , DefaultVerifier>
                {
                    TestState =
                    {
                        Sources = { inputSource },
                        GeneratedSources =
                        {
                            (typeof(DbContextInterfaceGenerator), "IUserBeanContext.g.cs", SourceText.From(expectedOutput, Encoding.UTF8))
                        }
                    }
                };

                // --- 加入以下這段 ---
                // 增加對 EF Core 的引用，否則生成的程式碼會報 CS0246 錯誤
                tester.ReferenceAssemblies = ReferenceAssemblies.Net.Net100
                    .WithPackages(System.Collections.Immutable.ImmutableArray.Create(
                        new PackageIdentity("Microsoft.EntityFrameworkCore" , "10.0.3")));
                var generatedCode = await tester.GetGeneratedCodeAsync("IUserBeanContext.g.cs");

                // 這裡可以直接斷言 generatedCode 是否與 expectedOutput 相同
                Assert.Multiple(() =>
                {
                    Assert.NotEmpty(generatedCode);

                    Assert.Contains("IUserBeanContext" , generatedCode);
                    Assert.Contains("namespace MyProject.Interfaces" , generatedCode);
                    Assert.Contains("UserBeans" , generatedCode);
                    Assert.Contains("自動生成的 UserBean 資料庫上下文介面" , generatedCode);
                });
        }
    }
    public class CSharpIncrementalGeneratorTest<TGenerator, TVerifier> : CSharpSourceGeneratorTest<TGenerator , TVerifier>
    where TGenerator : IIncrementalGenerator, new()
    where TVerifier : IVerifier, new()
    {
        protected override IEnumerable<Type> GetSourceGenerators() => new [ ] { typeof(TGenerator) };

        // 繞過那堆 EvaluatedProjectState，直接從 TestState 跑一次編譯
        public async Task<string> GetGeneratedCodeAsync(string targetFileName)
        {
            // 1. 建立 Solution (利用框架內部的邏輯，它會自己去處理 EvaluatedProjectState)
            // 注意：如果你的反組譯檔顯示 CreateSolutionAsync 是 protected，
            // 且需要專案 ID，我們可以從 TestState 獲取或模擬。

            // 較簡單的做法：呼叫基類的 GetProjectAsync (如果你的版本有這個方法)
            // 或是直接模擬 Generator 運行：
            var language = Language; // 來自 CSharpSourceGeneratorTest
            var fileName = $"/0/Test0.{DefaultFileExt}";
            var text = TestState.Sources [ 0 ].content;

            // 建立一個最基礎的 Ad-hoc 工作區來跑 Generator
            using var workspace = new AdhocWorkspace();
            var project = workspace.AddProject("TestProject" , language)
                .WithCompilationOptions(CreateCompilationOptions())
                .WithParseOptions(CreateParseOptions());

            // 加入原始碼
            project = project.AddDocument(fileName , text).Project;

            // 修正：不要直接存取 TestState.ReferenceAssemblies，因為它可能尚未從 Tester 同步
            var referenceAssemblies = TestState.ReferenceAssemblies ?? ReferenceAssemblies;

            if(referenceAssemblies == null)
            {
                throw new InvalidOperationException("ReferenceAssemblies must be set on either the Tester or TestState.");
            }

            // 加入必要的引用
            project = project.AddMetadataReferences(await referenceAssemblies.ResolveAsync(null , CancellationToken.None));

            var compilation = await project.GetCompilationAsync();

            // 2. 執行 Generator
            var generator = new TGenerator();
            var driver = Microsoft.CodeAnalysis.CSharp.CSharpGeneratorDriver.Create(generator);

            // 這裡要手動把 TestState 的配置餵進去，否則 VersionChecker 會拿不到資料
            // 如果你的 tester.TestState.AnalyzerConfigFiles 有資料，要在這裡轉換為 OptionsProvider

            driver.RunGeneratorsAndUpdateCompilation(compilation! , out var outputCompilation , out _);

            // 3. 找檔案
            var tree = outputCompilation.SyntaxTrees.FirstOrDefault(t => t.FilePath.EndsWith(targetFileName));
            return tree?.ToString() ?? "NotFound";
        }
    }
}
