<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
	  <TargetFrameworks>net10.0</TargetFrameworks>
	  <OutputType>Exe</OutputType>
	  <IsTestProject>true</IsTestProject>

	  <EnableMicrosoftTestingPlatform>true</EnableMicrosoftTestingPlatform>
	  <NUnitTestingPlatformEnable>true</NUnitTestingPlatformEnable>

	  <!--  
      <GenerateTestingPlatformEntryPoint>true</GenerateTestingPlatformEntryPoint>
      <GenerateSelfRegisteredExtensions>true</GenerateSelfRegisteredExtensions>
    -->	
	</PropertyGroup>
  <PropertyGroup>
    <EnableMicrosoftTestingPlatformEntryPoint>false</EnableMicrosoftTestingPlatformEntryPoint>
    <GenerateTestingPlatformEntryPoint>false</GenerateTestingPlatformEntryPoint>
    <EnableMicrosoftTestingPlatformExtensionsByCapability>false</EnableMicrosoftTestingPlatformExtensionsByCapability>
  </PropertyGroup>
  <!-- <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <PropertyGroup>
  -->
    <!-- 啟用 Microsoft.Testing.Platform -->
    <!-- <EnableMicrosoftTestingPlatform>true</EnableMicrosoftTestingPlatform> -->
    <!-- 使用Microsoft開發的Testing Platform Runner-->
    <!-- <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner> -->
    <!-- 告訴 NUnit 的 Adapter 把自己註冊到 MTP 引擎中 -->
    <!-- <NUnitTestingPlatformEnable>true</NUnitTestingPlatformEnable> -->
    <!-- 自動產生Testing Platform會執行的Entry point -->
    <!-- <GenerateTestingPlatformEntryPoint>true</GenerateTestingPlatformEntryPoint> -->
    <!-- 自動產生 Self Registered Extensions -->
    <!-- <GenerateSelfRegisteredExtensions>true</GenerateSelfRegisteredExtensions> -->
    <!-- 自動產生Program file -->
    <!-- <GenerateProgramFile>true</GenerateProgramFile> -->
  <!-- </PropertyGroup> -->
  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <!-- 移除它以避免舊引擎干擾 -->
    <!-- <PackageReference Include="Microsoft.NET.Test.Sdk" /> -->
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit.Analyzers" />
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="Microsoft.Testing.Platform.MSBuild" />  
    <PackageReference Include="Microsoft.NET.Test.Sdk" />  
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Moq" />
    <PackageReference Include="System.IO.Abstractions.TestingHelpers" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FluentAssertions" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Build" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="NUnit.Framework" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ProjectsVersionUtilityServices\ProjectsVersionUtilityServices.csproj" />
  </ItemGroup>
</Project>
