using System;
using System.Collections.Generic;
using System.IO.Abstractions;
using System.Text;
using static SolutionUtilityServices.PathExtensions;

namespace SolutionUtilityServices
{
    /// <summary>
    /// File extension checker
    /// </summary>
    public class FileExtensionChecker : IFileExtensionChecker
    {
        private static readonly HashSet<string> _configExt = new HashSet<string>
        {
            ".json" ,
            ".json5" ,
            ".config" ,
            ".xml" ,
            ".props" ,
        };
        private static readonly HashSet<string> _documentationExt = new HashSet<string>
        {
            ".md" ,
            ".docx",
            ".doc",
        };
        private static readonly HashSet<string> _solutionExt = new HashSet<string>
        {
            ".sln" ,
            ".slnx",
        };
        private static readonly HashSet<string> _projectExt = new HashSet<string>
        {
            ".csproj"
        };
        private static readonly HashSet<string> _programmingLanguageExt = new HashSet<string>
        {
            ".cs" , // C#
            ".g.cs", // C# generated by source generator
            ".vb", // visual basic
            ".fs", // F# source code
            ".fsx", // F# script
            ".fsi", // F# script interface
        };
        private static readonly HashSet<string> _textExt = new HashSet<string>
        {
            ".txt",
        };

        private static readonly IFileSystem _defaultFileSystem = new FileSystem();
        private readonly IFileSystem _fileSystem;
        public FileExtensionChecker(
            IFileSystem fileSystem
        )
        {
            _fileSystem = fileSystem ?? _defaultFileSystem;
        }
        public bool IsConfiguration(string filePath) => _fileSystem.File.Exists(filePath) && filePath.GetFileExtension().IsOneOf(_configExt);
        public bool IsDocument(string filePath) => _fileSystem.File.Exists(filePath) && filePath.GetFileExtension().IsOneOf(_documentationExt);
        public bool IsSolution(string filePath) => _fileSystem.File.Exists(filePath) && filePath.GetFileExtension().IsOneOf(_solutionExt);
        public bool IsProject(string filePath) => _fileSystem.File.Exists(filePath) && filePath.GetFileExtension().IsOneOf(_projectExt);
        public bool IsProgrammingLanguage(string filePath) => _fileSystem.File.Exists(filePath) && filePath.GetFileExtension().IsOneOf(_programmingLanguageExt);
        public bool IsText(string filePath) => _fileSystem.File.Exists(filePath) && filePath.GetFileExtension().IsOneOf(_textExt);
        public bool NeedsToBeReplaced(string filePath) =>
            IsConfiguration(filePath) ||
            IsDocument(filePath) ||
            IsSolution(filePath) ||
            IsProject(filePath) ||
            IsProgrammingLanguage(filePath) ||
            IsText(filePath);
    }
}
