<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="EnvironmentAbstractions" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.IO.Abstractions" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CliUtilityServices" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="EnvironmentUtilityServices" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\EnvironmentVariables.Core\EnvironmentVariables.Core.csproj" />
  </ItemGroup>
</Project>